[package]
name = "kimde"
version = "0.1.0"
authors = ["POMMI3R"]
edition = "2018"

[dependencies]
toml = "0.5.6"
serde = "1.0.116"
fantoccini = "0.14.1"
tokio = { version = "0.2.22", features = [ "macros", "tcp", "dns", "io-util" ] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3